════════════════════════════════════════
[2025-05-27 18:48:59.395] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-20 23:58:43.127] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 22:12:12.838] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 21:28:54.003] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 21:07:22.782] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 20:59:05.862] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 19:25:16.506] FIN DE SESIÓN
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 17:27:24.600] [ERROR]
Error al intentar reconectar al broker MQTT: Error while connecting with host 'broker.hivemq.com:1883'.
ERROR DETAILS:
  Message: Error while connecting with host 'broker.hivemq.com:1883'.
  StackTrace:    en MQTTnet.Implementations.CrossPlatformSocket.<ConnectAsync>d__29.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__17.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Internal.MqttTaskTimeout.<WaitAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__28.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en TFGv1_1.MQTTLogger.MQTTLoggerService.<>c__DisplayClass34_0.<<StartMQTTClient>b__1>d.MoveNext() en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1.MQTTLogger\MQTTLoggerService.cs:línea 1369
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 17:27:19.511] [ERROR]
Error al intentar reconectar al broker MQTT: Error while connecting with host 'broker.hivemq.com:1883'.
ERROR DETAILS:
  Message: Error while connecting with host 'broker.hivemq.com:1883'.
  StackTrace:    en MQTTnet.Implementations.CrossPlatformSocket.<ConnectAsync>d__29.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__17.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Internal.MqttTaskTimeout.<WaitAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__28.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en TFGv1_1.MQTTLogger.MQTTLoggerService.<>c__DisplayClass34_0.<<StartMQTTClient>b__1>d.MoveNext() en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1.MQTTLogger\MQTTLoggerService.cs:línea 1369
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 17:27:14.336] [ERROR]
Error al intentar reconectar al broker MQTT: Error while connecting with host 'broker.hivemq.com:1883'.
ERROR DETAILS:
  Message: Error while connecting with host 'broker.hivemq.com:1883'.
  StackTrace:    en MQTTnet.Implementations.CrossPlatformSocket.<ConnectAsync>d__29.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__17.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Internal.MqttTaskTimeout.<WaitAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__28.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en MQTTnet.Client.MqttClient.<ConnectAsync>d__34.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en TFGv1_1.MQTTLogger.MQTTLoggerService.<>c__DisplayClass34_0.<<StartMQTTClient>b__1>d.MoveNext() en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1.MQTTLogger\MQTTLoggerService.cs:línea 1369
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 03:41:55.014] [ERROR]
Error al limpiar alertas huérfanas
ERROR DETAILS:
  Message: Se agotó el tiempo de espera de ejecución. El período de tiempo de espera transcurrió antes de la finalización de la operación o el servidor no responde.
  StackTrace:    en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   en System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   en System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   en System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   en System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en TFGv1_1.MQTTLogger.MQTTLoggerService.<CleanupOrphanedAlerts>d__44.MoveNext() en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1.MQTTLogger\MQTTLoggerService.cs:línea 1921
════════════════════════════════════════
════════════════════════════════════════
[2025-05-13 03:41:55.005] [ERROR]
Error al verificar alertas
ERROR DETAILS:
  Message: Se agotó el tiempo de espera de ejecución. El período de tiempo de espera transcurrió antes de la finalización de la operación o el servidor no responde.
  StackTrace:    en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   en System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   en System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   en System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   en System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en TFGv1_1.MQTTLogger.MQTTLoggerService.<CheckAndCreateAlerts>d__26.MoveNext() en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1.MQTTLogger\MQTTLoggerService.cs:línea 1065
════════════════════════════════════════
[2025-05-13 17:27:33.014] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log' porque está siendo utilizado en otro proceso.
[2025-05-13 18:14:23.611] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 18:26:22.609] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 18:26:23.244] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 18:26:23.499] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 18:26:24.104] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 18:37:14.806] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 19:25:17.135] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 19:25:17.338] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 20:13:27.706] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 21:28:55.271] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log' porque está siendo utilizado en otro proceso.
[2025-05-13 22:12:13.306] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-13 22:12:16.860] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log' porque está siendo utilizado en otro proceso.
[2025-05-27 18:48:59.954] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\alerts.log' porque está siendo utilizado en otro proceso.
[2025-05-27 18:49:00.682] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log' porque está siendo utilizado en otro proceso.
[2025-05-27 18:49:03.495] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log' porque está siendo utilizado en otro proceso.
[2025-05-27 18:49:03.524] Error escribiendo en C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log: El proceso no puede obtener acceso al archivo 'C:\Users\josem\Desktop\Universidad\GreenHouseMonitor\TFGv1_1\Logs\service.log' porque está siendo utilizado en otro proceso.
